//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeemanagementApp.EmpMgmtSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseVoOfint", Namespace="http://schemas.datacontract.org/2004/07/Domain.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmployeemanagementApp.EmpMgmtSvc.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmployeemanagementApp.EmpMgmtSvc.Employee))]
    public partial class BaseVoOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/Domain.Models.Entities")]
    [System.SerializableAttribute()]
    public partial class Department : EmployeemanagementApp.EmpMgmtSvc.BaseVoOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Id")]
        public int Id1 {
            get {
                return this.Id1Field;
            }
            set {
                if ((this.Id1Field.Equals(value) != true)) {
                    this.Id1Field = value;
                    this.RaisePropertyChanged("Id1");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/Domain.Models.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmployeemanagementApp.EmpMgmtSvc.BaseVoOfint))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<EmployeemanagementApp.EmpMgmtSvc.Department>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmployeemanagementApp.EmpMgmtSvc.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<EmployeemanagementApp.EmpMgmtSvc.Employee>))]
    public partial class Employee : EmployeemanagementApp.EmpMgmtSvc.BaseVoOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Id")]
        public int Id1 {
            get {
                return this.Id1Field;
            }
            set {
                if ((this.Id1Field.Equals(value) != true)) {
                    this.Id1Field = value;
                    this.RaisePropertyChanged("Id1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpMgmtSvc.IEmployeeMgmtService")]
    public interface IEmployeeMgmtService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/CreateDepartment", ReplyAction="http://tempuri.org/IEmployeeMgmtService/CreateDepartmentResponse")]
        int CreateDepartment(string dept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/CreateDepartment", ReplyAction="http://tempuri.org/IEmployeeMgmtService/CreateDepartmentResponse")]
        System.Threading.Tasks.Task<int> CreateDepartmentAsync(string dept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/CreateEmployee", ReplyAction="http://tempuri.org/IEmployeeMgmtService/CreateEmployeeResponse")]
        int CreateEmployee(EmployeemanagementApp.EmpMgmtSvc.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/CreateEmployee", ReplyAction="http://tempuri.org/IEmployeeMgmtService/CreateEmployeeResponse")]
        System.Threading.Tasks.Task<int> CreateEmployeeAsync(EmployeemanagementApp.EmpMgmtSvc.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/DeleteDepartment", ReplyAction="http://tempuri.org/IEmployeeMgmtService/DeleteDepartmentResponse")]
        void DeleteDepartment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/DeleteDepartment", ReplyAction="http://tempuri.org/IEmployeeMgmtService/DeleteDepartmentResponse")]
        System.Threading.Tasks.Task DeleteDepartmentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/DeleteEmployee", ReplyAction="http://tempuri.org/IEmployeeMgmtService/DeleteEmployeeResponse")]
        void DeleteEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/DeleteEmployee", ReplyAction="http://tempuri.org/IEmployeeMgmtService/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/GetAllDepartments", ReplyAction="http://tempuri.org/IEmployeeMgmtService/GetAllDepartmentsResponse")]
        System.Collections.Generic.List<EmployeemanagementApp.EmpMgmtSvc.Department> GetAllDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/GetAllDepartments", ReplyAction="http://tempuri.org/IEmployeeMgmtService/GetAllDepartmentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EmployeemanagementApp.EmpMgmtSvc.Department>> GetAllDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/ReadDepartment", ReplyAction="http://tempuri.org/IEmployeeMgmtService/ReadDepartmentResponse")]
        EmployeemanagementApp.EmpMgmtSvc.Department ReadDepartment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/ReadDepartment", ReplyAction="http://tempuri.org/IEmployeeMgmtService/ReadDepartmentResponse")]
        System.Threading.Tasks.Task<EmployeemanagementApp.EmpMgmtSvc.Department> ReadDepartmentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/GetAllEmployees", ReplyAction="http://tempuri.org/IEmployeeMgmtService/GetAllEmployeesResponse")]
        System.Collections.Generic.List<EmployeemanagementApp.EmpMgmtSvc.Employee> GetAllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/GetAllEmployees", ReplyAction="http://tempuri.org/IEmployeeMgmtService/GetAllEmployeesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EmployeemanagementApp.EmpMgmtSvc.Employee>> GetAllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/ReadEmployee", ReplyAction="http://tempuri.org/IEmployeeMgmtService/ReadEmployeeResponse")]
        EmployeemanagementApp.EmpMgmtSvc.Employee ReadEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/ReadEmployee", ReplyAction="http://tempuri.org/IEmployeeMgmtService/ReadEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeemanagementApp.EmpMgmtSvc.Employee> ReadEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/UpdateDepartment", ReplyAction="http://tempuri.org/IEmployeeMgmtService/UpdateDepartmentResponse")]
        void UpdateDepartment(EmployeemanagementApp.EmpMgmtSvc.Department dept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/UpdateDepartment", ReplyAction="http://tempuri.org/IEmployeeMgmtService/UpdateDepartmentResponse")]
        System.Threading.Tasks.Task UpdateDepartmentAsync(EmployeemanagementApp.EmpMgmtSvc.Department dept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeMgmtService/UpdateEmployeeResponse")]
        void UpdateEmployee(EmployeemanagementApp.EmpMgmtSvc.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeMgmtService/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeMgmtService/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task UpdateEmployeeAsync(EmployeemanagementApp.EmpMgmtSvc.Employee emp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeMgmtServiceChannel : EmployeemanagementApp.EmpMgmtSvc.IEmployeeMgmtService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeMgmtServiceClient : System.ServiceModel.ClientBase<EmployeemanagementApp.EmpMgmtSvc.IEmployeeMgmtService>, EmployeemanagementApp.EmpMgmtSvc.IEmployeeMgmtService {
        
        public EmployeeMgmtServiceClient() {
        }
        
        public EmployeeMgmtServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeMgmtServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeMgmtServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeMgmtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateDepartment(string dept) {
            return base.Channel.CreateDepartment(dept);
        }
        
        public System.Threading.Tasks.Task<int> CreateDepartmentAsync(string dept) {
            return base.Channel.CreateDepartmentAsync(dept);
        }
        
        public int CreateEmployee(EmployeemanagementApp.EmpMgmtSvc.Employee emp) {
            return base.Channel.CreateEmployee(emp);
        }
        
        public System.Threading.Tasks.Task<int> CreateEmployeeAsync(EmployeemanagementApp.EmpMgmtSvc.Employee emp) {
            return base.Channel.CreateEmployeeAsync(emp);
        }
        
        public void DeleteDepartment(int id) {
            base.Channel.DeleteDepartment(id);
        }
        
        public System.Threading.Tasks.Task DeleteDepartmentAsync(int id) {
            return base.Channel.DeleteDepartmentAsync(id);
        }
        
        public void DeleteEmployee(int id) {
            base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(int id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
        
        public System.Collections.Generic.List<EmployeemanagementApp.EmpMgmtSvc.Department> GetAllDepartments() {
            return base.Channel.GetAllDepartments();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EmployeemanagementApp.EmpMgmtSvc.Department>> GetAllDepartmentsAsync() {
            return base.Channel.GetAllDepartmentsAsync();
        }
        
        public EmployeemanagementApp.EmpMgmtSvc.Department ReadDepartment(int id) {
            return base.Channel.ReadDepartment(id);
        }
        
        public System.Threading.Tasks.Task<EmployeemanagementApp.EmpMgmtSvc.Department> ReadDepartmentAsync(int id) {
            return base.Channel.ReadDepartmentAsync(id);
        }
        
        public System.Collections.Generic.List<EmployeemanagementApp.EmpMgmtSvc.Employee> GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EmployeemanagementApp.EmpMgmtSvc.Employee>> GetAllEmployeesAsync() {
            return base.Channel.GetAllEmployeesAsync();
        }
        
        public EmployeemanagementApp.EmpMgmtSvc.Employee ReadEmployee(int id) {
            return base.Channel.ReadEmployee(id);
        }
        
        public System.Threading.Tasks.Task<EmployeemanagementApp.EmpMgmtSvc.Employee> ReadEmployeeAsync(int id) {
            return base.Channel.ReadEmployeeAsync(id);
        }
        
        public void UpdateDepartment(EmployeemanagementApp.EmpMgmtSvc.Department dept) {
            base.Channel.UpdateDepartment(dept);
        }
        
        public System.Threading.Tasks.Task UpdateDepartmentAsync(EmployeemanagementApp.EmpMgmtSvc.Department dept) {
            return base.Channel.UpdateDepartmentAsync(dept);
        }
        
        public void UpdateEmployee(EmployeemanagementApp.EmpMgmtSvc.Employee emp) {
            base.Channel.UpdateEmployee(emp);
        }
        
        public System.Threading.Tasks.Task UpdateEmployeeAsync(EmployeemanagementApp.EmpMgmtSvc.Employee emp) {
            return base.Channel.UpdateEmployeeAsync(emp);
        }
    }
}
